DELETE FROM articles;
DELETE FROM users_roles;
DELETE FROM users;
DELETE FROM roles;

ALTER TABLE articles AUTO_INCREMENT = 1;
ALTER TABLE roles AUTO_INCREMENT = 1;
ALTER TABLE users AUTO_INCREMENT = 1;
ALTER TABLE users_roles AUTO_INCREMENT = 1;